# Generated by Django 4.0.5 on 2022-07-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('documentos', models.BooleanField(default=False)),
                ('fecha_creado', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloDocumentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=40)),
                ('mes', models.CharField(max_length=40)),
                ('año', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metododepago', models.CharField(max_length=40)),
                ('pagado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeloTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramite', models.CharField(choices=[['Apostilla', 'Apostilla'], ['Partidas', 'Partidas'], ['Residencia Uruguaya', 'Residencia Uruguaya'], ['Titulos de Estudio', 'Titulos de Estudio'], ['DNI', 'DNI'], ['Pasaporte', 'Pasaporte'], ['Turnos visados', 'Turnos visados'], ['Otro', 'Otro']], max_length=40)),
            ],
        ),
    ]
